### PR TITLE
Migrate The Post service into Postgres

### PR DESCRIPTION
**Pull request by daveaugustus**
Signed-off-by: Dave Augustus <davetweetlive@gmail.com>

### CODE REVIEW

**Review by DhanushNehru — COMMENTED** [review]
Why migrating to postgre @daveaugustus ?

**Comment by daveaugustus** [comment]
@DhanushNehru I have decided to keep The blogs in Postgres and the replica of the data in OpenSearch maintaining the consistency so we can be less worried about the data backup.

If you have a better suggestion, do let me know.

**Comment by DhanushNehru** [comment]
The storage in opensearch would be NoSQL type ( we can store unstructured data ), whereas in Postgres it would be SQL type ( the data stored will be structured ) . In case you are taking backup wont there be any contradiction between the storage of data !!!!

Either I can suggest you MongoDB ( NoSQL ) or you can go with Postgres which purely depends on what structure you would like to store as things progress

**Comment by DhanushNehru** [comment]
@daveaugustus  The storage in opensearch would be NoSQL type ( we can store unstructured data ), whereas in Postgres it would be SQL type ( the data stored will be structured ) . In case you are taking backup wont there be any contradiction between the storage of data !!!!

Either I can suggest you MongoDB ( NoSQL ) or you can go with Postgres which purely depends on what structure you would like to store as things progress

**Pull request closed without merging**
